version: "3.8"

services: 
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - 3000:3000
    depends_on: 
      mysql_server:
        condition: service_healthy
     
  
  mysql_server:
    image: mysql:8.0
    ports: 
      - 3306:3306
    expose:
      - 3306
    environment: 
      - MYSQL_DATABASE=db_daily_report
      - MYSQL_USER=report_root
      - MYSQL_PASSWORD=Uneatlantico22
      - MYSQL_ROOT_PASSWORD=Uneatlantico22s
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 3s
            retries: 10