swagger: "2.0"
info:
  description: "Este será un contrato del backend para la herramienta de daily Reports"
  version: "1.0.0"
  title: "Daily Reports API"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "petstore.swagger.io"
basePath: "/v2"




tags:
- name: "Herramientas"
  description: "El crud completo para las herramientas."


schemes:
- "http"



paths:
  
  
  /api/herras:
    get:
      tags:
      - "Herramientas"
      summary: "Devulve todas las herrramientas de la aplicación."
      operationId: "getHerramientas"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Es el esquema para poder obtener a todas las herramientas."
        required: true
        schema:
          $ref: "#/definitions/Herramienta"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "object"
            additionalProperties:
              type: "integer"
              format: "int32"
      
    post:
      tags:
      - "Herramientas"
      summary: "Es la ruta para crear una nueva herramienta dentro de la aplicación."
      operationId: "postHerramienta"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Formato para crear una nueva herramienta."
        required: true
        schema:
          $ref: "#/definitions/Herramienta"
      responses:
        "201":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Herramienta"
        "400":
          description: "Invalid Herramienta"
          
          
          
          
  /api/herras{herraId}:
    get:
      tags:
      - "Herramientas"
      summary: "Busca una herramienta por ID específico."
      operationId: "getHerramientaById"
      produces:
      - "application/json"
      parameters:
      - name: "herraId"
        in: "path"
        description: "Sirve para buscar una herramienta en específico."
        required: true
        type: "integer"
        maximum: 100.0
        minimum: 1.0
        format: "int64"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Herramienta"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Herramienta not found"
    
    
    put:
      tags:
      - "Herramientas"
      summary: "Actualiza una herramienta por ID específico."
      operationId: "putHerramientaById"
      produces:
      - "application/json"
      parameters:
      - name: "herraId"
        in: "path"
        description: "Sirve para buscar una herramienta en específico."
        required: true
        type: "integer"
        maximum: 100.0
        minimum: 1.0
        format: "int64"
      - in: "body"
        name: "body"
        description: "Esquema para actualizar una herramienta de la aplicación."
        required: true
        schema:
          $ref: "#/definitions/Herramienta"
        
        
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Herramienta"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Herramienta not found"      
          
          
    delete:
      tags:
      - "Herramientas"
      summary: "Elimina una herramienta de la aplicación."
      operationId: "deleteHerramienta"
      produces:
      - "application/json"
      parameters:
      - name: "herraId"
        in: "path"
        description: "ID of the order that needs to be deleted"
        required: true
        type: "integer"
        minimum: 1.0
        format: "int64"
      responses:
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Order not found"
 
 
 

 
definitions:
      
  
  
  Herramienta:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      tipo:
        type: "string"
        enum:
        - "Software"
        - "Hardware"
      nombre:
        type: "string"
        
    xml:
      name: "Order"  

  
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"
        
        
        
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
  
  
  
  
  
  